---
- name: Install zsh in Redhat derivatives
  become: true
  yum: name=zsh state=installed
  when: ansible_os_family == 'RedHat'

- name: Install zsh in Debian derivatives
  become: true
  apt: pkg=zsh state=present
  when: ansible_os_family == 'Debian'

- name: Install zsh in Arch Linux derivatives
  pacman: name=zsh state=present
  become: true
  when: ansible_os_family == 'Arch Linux'

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  become: true
  become_user: "{{ oh_my_zsh_user }}"

- name: Copy .zshrc to $HOME
  template:
    src: zshrc.j2
    dest: ~/.zshrc
  become: true
  become_user: "{{ oh_my_zsh_user }}"

- name: switch to ZSH
  user: name={{ oh_my_zsh_user }} shell=/usr/bin/zsh
  become: true
  when: ansible_os_family != 'Darwin'

- name: Switch to ZSH (OSX)
  command: chsh -s /bin/zsh
  become: true
  when: ansible_os_family == 'Darwin'
