---

- name: install zsh
  apt: pkg=zsh state=present

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  sudo: false

- name: Checking up existing ~/.zshrc
  stat: path=~{{user}}/.zshrc
  register: st

- name: Backing up existing ~/.zshrc
  copy: source=~{{user}}/.zshrc dest=~{{user}}.orig
  sudo: false
  when: st.stat.isfile is defined and st.stat.isfile == true

- name: Creating new ~/.zshrc
  copy: src=~{{user}}/.oh-my-zsh/templates/zshrc.zsh-template dest=~{{user}}/.zshrc
  sudo: false

- name: Add oh-my-solarized theme
  copy: src=oh-my-zsh.theme dest=~{{user}/.oh-my-zsh/themes/oh-my-zsh.theme
  sudo: false

- name: switch to ZSH
  user: name={{user}} shell=/usr/bin/zsh
  sudo: True
