---

- name: install zsh
  apt: pkg=zsh state=present

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

- name: Backing up existing ~/.zshrc
  command: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi

- name: Creating new ~/.zshrc
  command: cp /home/{{user}}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{user}}/.zshrc

- name: Add oh-my-solarized theme
  copy: src=files/oh-my-zsh.theme dest=/home/{{user}/.oh-my-zsh/themes/oh-my-zsh.theme

- name: switch to ZSH
  user: name={{user}} shell=/usr/bin/zsh
  sudo: True
